config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'about#index'

  get '/terms', to: 'terms#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new', as: 'sign-up'

  post "sign-up", to: "registrations#create"

  get 'sign-in', to: "authentication#new"

  post 'sign-in', to: "authentication#create"

  get 'sign-out', to: 'authentication#destroy'

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resources :trackers, only: [:show]

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :description, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :restrict_task_access

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def show
    @task = @project.tasks.find(params[:id])
    @comments = @task.comments.all
    @comment = Comment.new
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    project_task = @project.tasks.find(params[:id])
    project_task.destroy
    redirect_to project_tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:description, :completed, :due_date)
  end

  def restrict_task_access
    unless @project.memberships.include?(current_user.memberships.find_by(project_id: @project.id)) || current_user.is_admin?
      flash[:error] = "You do not have access to that project"
      redirect_to projects_path
    end
  end

end

app/views/tasks/_form.html.erb
<%= render partial: "shared/errors", locals: { object: @task } %>

<%= form_for([@project, @task], html: {class: 'form-horizontal'}) do |f| %>

  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-md-6">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date , class: "col-sm-2 control-label"%>
    <div class="col-md-3">
      <%= f.date_field :due_date, class: "form-control" %>
    </div>
  </div>

  <% unless @task.new_record? %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.check_box :completed %>
        <%= f.label :completed %>
      </div>
    </div>
  <% end %>

  <div class="actions form-group">
    <div class='col-md-4 col-sm-offset-2'><%= f.submit name_of_button, class: "btn btn-primary" %>
      <%= link_to 'cancel', project_tasks_path, class: 'btn btn-default' %></div>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Edit Task</h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to "#{@project.name}", project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project, @tasks) %></li>
  <li><%= link_to "#{@task.description}", project_task_path(@project, @task) %></li>
  <li class="active">Edit</li>
</ul>

<%= render partial: 'form', locals: { name_of_button: "Update Task"} %>

app/views/tasks/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New Task", new_project_task_path(@project), class: 'btn btn-info' %>
  </div>
  <h1><%= "Tasks for #{@project.name}" %></h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to "#{@project.name}", project_path(@project) %></li>
  <li class="active">Tasks</li>
</ul>

<table class="table">

  <thead>
    <tr>
      <th>Description</th>
      <th>Due on</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>

        <td class="col-md-3">
          <% if task.completed %>
            <s><%= link_to task.description, project_task_path(@project, task) %></s> <span class="badge"><%= task.comments.count %></span>
          <% else %>
            <%= link_to task.description, project_task_path(@project, task) %> <span class="badge"><%= task.comments.count %></span>
          <% end %>
        </td>

        <td>
          <% if task.due_date %>
            <%= task.due_date.strftime("%m/%d/%Y") %>
          <% end %>
        </td>

        <td>
          <div class="pull-right">
            <%= link_to "Edit", edit_project_task_path(@project, task), class: 'btn btn-info text-right' %>
            <%= link_to "", project_task_path(@project, task), method: :delete, class: "glyphicon glyphicon-remove" %>
          </div>
        </td>

      </tr>

    <% end %>

  </tbody>

</table>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to "#{@project.name}", project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project, @tasks) %></li>
  <li class="active">New</li>
</ul>

<%= render partial: "form", locals: { name_of_button: "Create Task"} %>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "Edit", edit_project_task_path(@project, @task), class: 'btn btn-info' %>
  </div>
  <% if @task.completed %>
    <h1><s><%= @task.description %></s></h1>
  <% else %>
  <h1> <%= @task.description %> </h1>
  <% end %>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to "#{@project.name}", project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project, @tasks) %></li>
  <li class="active"><%= @task.description %></li>
</ul>

<p>
<strong>Due On:</strong>
<% if @task.due_date %>
  <%= @task.due_date.strftime("%m/%d/%Y") %>
<% end %>
</p>

<h3>Comments</h3>

  <% @comments.each do |comment| %>
    <div class="row">
      <div class="col-md-3">
        <% if comment.user_id %>
          <%= link_to "#{comment.user.first_name} #{comment.user.last_name}", user_path(comment.user) %>
        <% else %>
          (deleted user)
        <% end %>
        <p class="text-muted">
          <%= time_ago_in_words(comment.created_at) %>
        </p>
      </div>
      <div class="col-md-9">
        <%= comment.body %>
      </div>
    </div>
  <% end %>


<%= form_for([@task, @comment]) do |f| %>
  <div class="row">
    <div class="form-group col-md-offset-3 col-md-9">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-offset-3 col-md-9">
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>