config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'about#index'

  get '/terms', to: 'terms#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new', as: 'sign-up'

  post "sign-up", to: "registrations#create"

  get 'sign-in', to: "authentication#new"

  post 'sign-in', to: "authentication#create"

  get 'sign-out', to: 'authentication#destroy'

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resources :trackers, only: [:show]

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :memberships, dependent: :destroy
  has_many :projects, through: :memberships
  has_many :comments, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

  def full_name
    "#{self.first_name}" + " #{self.last_name}"
  end

  def is_owner?(project)
    self.memberships.find_by(project_id: project.id) && self.memberships.find_by(project_id: project.id).role_id == 1 || self.is_admin?
  end

  def is_member?(membership)
    self.id == membership.user_id || self.is_admin?
  end

  def is_admin?
    self.admin == true
  end

  def co_member?(user)
    user.projects.map { |project| project.users }.flatten.include?(self)
  end

  def tracker_token
    unless self.token == nil
      "#{token[0..3]}***********************"
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :only_change_own_user_profile, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "User was successfully created"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: "User was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if current_user.id == user.id
      User.destroy(params[:id])
      session.clear
      redirect_to root_path
    else
      User.destroy(params[:id])
      redirect_to users_path
    end
  end

  private

  def user_params
    if current_user.is_admin?
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :admin, :token)
    else
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :token)
    end
  end

  def only_change_own_user_profile
    @user = User.find(params[:id])
    unless current_user.id == @user.id || current_user.is_admin?
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end

end

app/views/users/_form.html.erb
<%= render partial: "shared/errors", locals: { object: @user } %>


<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>

  <div class="form-group">
    <%= f.label :first_name, "First Name", class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.text_field :first_name, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :last_name, "Last Name", class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.text_field :last_name, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.text_field :email, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.password_field :password, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Password Confirmation", class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.password_field :password_confirmation, class: 'form-control' %></div>
  </div>

  <div class="form-group">
    <%= f.label :token, "Pivotal Tracker Token", class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.text_field :token, class: 'form-control' %></div>
  </div>

  <% if current_user.is_admin? %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <div class="checkbox">
          <label>
            <%= f.check_box :admin %> Admin
          </label>
        </div>
      </div>
    </div>
  <% end %>

  <div class="actions form-group">
    <div class="col-md-4 col-sm-offset-2">
      <%= f.submit name_of_button, class: "btn btn-primary" %>
      <%= link_to "Cancel", users_path, class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit User</h1>
</div>

<%= render partial: "form", locals: { name_of_button: "Update User" } %>

<div class="well col-md-6 col-sm-offset-2 text-center">
  <%= link_to "Delete User", user_path, method: "delete", class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
</div>

app/views/users/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New User", new_user_path, class: 'btn btn-info' %>
  </div>
  <h1>Users</h1>
</div>

<table class="table">

  <thead>
    <tr>
      <th class="col-md-2">Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
      </td>
      <td>
        <% if current_user.id == user.id || current_user.co_member?(user) || current_user.is_admin? %>
          <%= mail_to user.email %>
        <% end %>
      </td>
      <td>
        <% if current_user.id == user.id || current_user.is_admin? %>
          <div class="pull-right">
            <%= link_to "Edit", edit_user_path(user) %>
          </div>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>New User</h1>
</div>

<%= render partial: "form", locals: { name_of_button: "Create User" }%>

app/views/users/show.html.erb
<div class="page-header">
  <% if current_user.id == @user.id %>
    <div class="pull-right">
      <%= link_to "Edit", edit_user_path, class: 'btn btn-info' %>
    </div>
  <% end %>
  <h1><%= @user.first_name %> <%= @user.last_name %></h1>
</div>


<dl class="dl-horizontal">
  <dt>First Name</dt>
  <dd><%= @user.first_name %></dd>
  <dt>Last Name</dt>
  <dd><%= @user.last_name %></dd>
  <% if current_user.id == @user.id || current_user.co_member?(@user) %>
    <dt>Email</dt>
    <dd> <%= mail_to @user.email %> </dd>
  <% end %>
  <dt>Pivotal Tracker Token</dt>
  <dd><%= @user.tracker_token %></dd>
</dl>