config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'about#index'

  get '/terms', to: 'terms#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new', as: 'sign-up'

  post "sign-up", to: "registrations#create"

  get 'sign-in', to: "authentication#new"

  post 'sign-in', to: "authentication#create"

  get 'sign-out', to: 'authentication#destroy'

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resources :trackers, only: [:show]

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :member_must_be_owner, only: [:edit, :update, :destroy]
  before_action :restrict_project_access, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.is_admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end
    tracker_api = TrackerAPI.new
    if current_user.token
      if tracker_api.projects(current_user.token).class == Array
        @tracker_projects = tracker_api.projects(current_user.token)
      else
        flash[:error] = "Your token is invalid. Please enter a valid tracker token."
        @tracker_projects = {}
      end
    end
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      @project.memberships.create(project_id: @project.id, user_id: current_user.id, role_id: 1)
      redirect_to project_tasks_path(@project), notice: "Project was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Project was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    Project.destroy(params[:id])
    redirect_to projects_path, notice: "Project was successfully deleted"
  end


  private

  def project_params
    params.require(:project).permit(:name)
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def member_must_be_owner
    unless current_user.is_owner?(@project) #unless this is true
      flash[:error] = 'You do not have access'
      redirect_to project_path(@project)
    end
  end

  def restrict_project_access
    unless @project.memberships.include?(current_user.memberships.find_by(project_id: @project.id)) || current_user.is_admin?
      flash[:error] = "You do not have access to this project"
      redirect_to projects_path
    end
  end

end

app/views/projects/_form.html.erb
<%= render partial: "shared/errors", locals: { object: @project } %>

<%= form_for(@project, html: {class: 'form-horizontal'}) do |f| %>

  <div class="field form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-md-6"><%= f.text_field :name, class: "form-control" %></div>
  </div>

  <div class="actions form-group">
    <div class="col-md-4 col-sm-offset-2">
      <%= f.submit name_of_button, class: "btn btn-primary" %>
      <%= link_to "Cancel", projects_path, class: "btn btn-default" %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to "#{@project.name}", project_path(@project) %></li>
  <li class="active">Edit</li>
</ul>

<%= render partial: "form", locals: { name_of_button: "Update Project"} %>

app/views/projects/index.html.erb
<div class="page-header">
  <div class="pull-right">
      <%= link_to "New Project", new_project_path, class: 'btn btn-info' %>
  </div>
  <h1>Projects</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th class="col-md-8">Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project|  %>
    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= link_to "#{project.tasks.count}", project_tasks_path(project) %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<div class="page-header">
  <h1>Pivotal Tracker Projects</h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <% if current_user.token %>
    <% @tracker_projects.each do |project| %>
    <tr>
      <th><%= link_to project[:name], tracker_path(project[:id], name: project[:name]) %></th>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li class="active">New Project</li>
</ul>

<%= render partial: "form", locals: { name_of_button: "Create Project"} %>

app/views/projects/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <% if current_user.is_owner?(@project) %>
      <%= link_to "Edit", edit_project_path(@project), class: 'btn btn-info' %>
    <% end %>
  </div>
  <h1><%= @project.name %></h1>
</div>

<ul class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li class="active"><%= "#{@project.name}" %></li>
</ul>

<p><%= link_to "#{pluralize(@project.tasks.count, 'Task')}", project_tasks_path(@project, @task) %></p>
<p>
  <%= link_to "#{pluralize(@project.memberships.count, 'Membership')}", project_memberships_path(@project, @membership) %>
</p>


<% if current_user.is_owner?(@project) %>
  <div class="well">
    <h3>Delete Project</h3>
    <p>
      Deleting this project will also delete <%= "#{pluralize(@project.memberships.count, 'membership')}, #{pluralize(@project.tasks.count, 'task')}" %> and associated comments.
    </p>

    <%= link_to "Delete", project_path, method: "delete", class: "btn btn-danger", data: { confirm: "Are you sure?" } %>

  </div>
<% end %>