config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/about', to: 'about#index'

  get '/terms', to: 'terms#index'

  get '/faq', to: 'common_questions#index'

  get 'sign-up', to: 'registrations#new', as: 'sign-up'

  post "sign-up", to: "registrations#create"

  get 'sign-in', to: "authentication#new"

  post 'sign-in', to: "authentication#create"

  get 'sign-out', to: 'authentication#destroy'

  resources :users

  resources :projects do
    resources :tasks
    resources :memberships, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :tasks do
    resources :comments, only: [:new, :create]
  end

  resources :trackers, only: [:show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "gCamp", projects_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav dropdown">
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Project <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% @my_projects.each do |project| %>

              <li><%= link_to "#{project.name}", project_path(project) %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "New Project", new_project_path %></li>
          </ul>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %></li>
          <li><%= link_to "Sign Out", sign_out_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>

    </div>

  </nav>

  <div class="container">

      <% if notice %>
        <div id="notice" class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <% if flash[:error] %>
        <div id="notice" class="alert alert-danger" role="alert">
          <%= flash[:error] %>
        </div>
      <% end %>

    <%= yield %>

    <footer class="footer">
      <p class="text-center">
          <%= link_to "Home", root_path %> |
          <%= link_to "About", about_path %> |
          <%= link_to "Terms", terms_path %> |
          <%= link_to "FAQ", faq_path %>
      </p>
    </footer>


  </div><!--container-->

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gcamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
    <div class="container container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to "gCamp", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %></li>
          <li><%= link_to "Sign Out", sign_out_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="container">

    <% if notice %>
      <div id="notice" class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if flash[:error] %>
      <div id="notice" class="alert alert-danger" role="alert">
        <%= flash[:error] %>
      </div>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <div class="left_justify">
        <% if current_user %>
          <%= link_to "About", about_path %> |
          <%= link_to "Terms", terms_path %> |
          <%= link_to "FAQ", faq_path %> |
          <%= link_to "Users", users_path %> |
          <%= link_to "Projects", projects_path %>
        <% else %>
          <%= link_to "About", about_path %> |
          <%= link_to "Terms", terms_path %> |
          <%= link_to "FAQ", faq_path %>
        <% end %>
      </div>
      
      <div class="right_justify">
        <div class="badges">
          <%= link_to "http://www.linkedin.com/in/kathrynkilianvovk/" do %>
            <%= image_tag("linked_in.jpg", height:'30') %>
          <% end %>
        </div>
        <div class="badges">
          <%= link_to "https://www.github.com/katekilianvovk" do %>
            <%= image_tag("GitHub.png", height:'30') %>
          <% end %>
        </div>
        <div class="badges">
          <%= link_to "https://twitter.com/katekilianvovk" do %>
            <%= image_tag("Twitter.png", height:'30') %>
          <% end %>
        </div>
        <div class="badges">
          <%= link_to "https://students.gschool.it/students/285" do %>
            <%= image_tag("galvanize.png", height:'30') %>
          <% end %>
        </div>
      </div>
    </footer>

  </div>


</body>

</html>